package br.ufg.softconc.montanharussa;

public class GeradorPessoa {
	private static final String[] nomes = new String[]{
			"Woody Franks",
			"Hayden Hoffman",
			"Humaira Tomlinson",
			"Rudy Seymour",
			"Amaan Ryder",
			"Alesha Sears",
			"Suhayb Weber",
			"Kara Kaiser",
			"Cali Emery",
			"Ryker Allman",
			"Tudor Carey",
			"Sofie Barnes",
			"Yousuf Calhoun",
			"Kofi Harper",
			"Simon Cote",
			"Kody Markham",
			"Sanaa Pierce",
			"Angelica Millington",
			"Dylon Ortega",
			"Nicole Dolan",
			"Dottie Hayes",
			"Shivani Kirkpatrick",
			"Nafeesa Beard",
			"Keira Bender",
			"Leonie Randolph",
			"Mccauley Moon",
			"Denny Plummer",
			"Bertie Gregory",
			"Chester Rubio",
			"Darren Carroll",
			"Ozan Casey",
			"Ruby Smart",
			"Kornelia Velasquez",
			"Riley-James Odonnell",
			"Alessia Santos",
			"Kathleen Bentley",
			"Louise Mays",
			"Amalie Nichols",
			"Michelle Herbert",
			"Meghan Stokes",
			"Leanne Enriquez",
			"Elwood Kumar",
			"Marni Cash",
			"Lewie Sheehan",
			"Marta Metcalfe",
			"Luci Clemons",
			"Della Power",
			"Ishika Nicholson",
			"Rares Sumner",
			"Qasim Rasmussen",
			"Todd Hassan",
			"Amelia-Mae Palacios",
			"Kerri Pollard",
			"Timur Bauer",
			"Reggie West",
			"Ty Adkins",
			"Elowen Blake",
			"Abu Mcgrath",
			"Shelley Parry",
			"Eddison Green",
			"Ishaan Ward",
			"Pranav Cotton",
			"Christian Macdonald",
			"Nathalie Lucero",
			"Arandeep Graves",
			"Cieran Lugo",
			"Alys Espinoza",
			"Ameera Sharples",
			"Sarah Cordova",
			"Murtaza Corrigan",
			"Manisha Couch",
			"Aqsa Dowling",
			"Natan Castillo",
			"Emilee Waller",
			"Jardel Wolf",
			"Ruben Cooper",
			"Rosa Wilkes",
			"Hiba Hendricks",
			"Florrie May",
			"Montana Garrison",
			"Kasey Walters",
			"Caspar Bell",
			"Sabah Ahmad",
			"Neve Martinez",
			"Dennis Turnbull",
			"Amy-Louise Berg",
			"Danielius Combs",
			"Lawrence Grainger",
			"Amin Ferrell",
			"Adriana Olson",
			"Maleeha Bateman",
			"Clinton Whitley",
			"Tashan John",
			"Tobey Duran",
			"Cory Sutherland",
			"Nia Welsh",
			"Zakaria Sims",
			"Aine Burch",
			"Sean Guerrero",
			"Lainey Thorne",
	};

	public Pessoa novaPessoa() {
		return new Pessoa(nomeAleatorio());
	}

	private String nomeAleatorio() {
		int i = (int) Math.floor(nomes.length * Math.random());
		return nomes[i];
	}
}
